In [1]:
import pandas as pd

In [2]:
incident_data = pd.read_csv("../../clean_data/florida_incident_data_w_categories.csv")
valid_incident_data = pd.read_csv("../../clean_data/valid_incident_weather_info.csv")
invalid_incident_data = pd.read_csv("../../clean_data/valid_incident_weather_info.csv")

In [11]:
valid_incident_info = incident_data[["ID", "incident_type"]]

In [15]:
valid_incident_data

,date,weather_code,temperature_2m_mean,temperature_2m_max,temperature_2m_min,apparent_temperature_mean,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,...,wind_speed_10m_max,wind_gusts_10m_max,shortwave_radiation_sum,et0_fao_evapotranspiration,relative_humidity_2m_mean,relative_humidity_2m_max,relative_humidity_2m_min,soil_moisture_0_to_100cm_mean,soil_temperature_0_to_100cm_mean,associated_incident_id
0,2025-09-05 00:00:00+00:00,61.0,26.181250,30.853739,23.222721,31.119635,37.405216,27.646168,3.700000,3.700000,...,15.685840,32.760002,20.340000,4.081936,86.535942,97.319748,67.104454,0.100330,27.059708,2.025099e+09
1,2025-09-08 00:00:00+00:00,65.0,24.831251,28.726011,22.698296,29.675135,34.100143,27.605642,40.900002,40.900002,...,11.032987,32.760002,13.220000,2.638540,91.182335,98.795929,76.686935,0.111966,27.282877,2.025099e+09
2,2025-09-08 00:00:00+00:00,63.0,25.320002,28.822502,23.418974,29.850115,32.781475,27.737570,13.900000,13.900000,...,18.391737,39.599998,16.770000,3.193541,90.186157,98.799850,72.203178,0.178233,26.044960,2.025099e+09
3,2025-09-10 00:00:00+00:00,63.0,24.968752,30.912399,22.292822,29.667816,36.358009,26.794775,8.700001,8.700001,...,11.903159,29.879999,15.740000,3.191597,89.921196,100.000000,65.571266,0.135140,26.326019,2.025099e+09
4,2025-09-11 00:00:00+00:00,63.0,26.777082,28.501064,24.950001,31.184931,32.895767,29.445236,9.800000,9.800000,...,21.252962,45.360001,16.320000,3.356593,85.609283,93.624374,77.118385,0.185335,27.878496,2.025099e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2016-07-06 00:00:00+00:00,61.0,28.930170,32.800346,25.011164,35.103939,41.161266,30.888229,3.500000,3.500000,...,13.684735,23.039999,23.700001,5.090987,80.441078,95.925018,64.424858,0.221687,28.096649,2.016076e+09
1455,2016-07-06 00:00:00+00:00,51.0,29.559919,35.065079,24.764378,34.819813,40.718952,30.542171,0.400000,0.400000,...,9.659814,27.359999,23.410000,5.393454,72.999016,97.347054,49.744556,0.162852,27.800879,2.016076e+09
1456,2016-07-06 00:00:00+00:00,51.0,28.985748,30.460400,26.847189,35.060455,38.243690,32.108582,0.100000,0.100000,...,17.102840,23.759998,24.240000,5.076493,81.179146,89.624519,74.539909,0.213385,28.357355,2.016076e+09
1457,2016-07-08 00:00:00+00:00,53.0,29.020836,31.750908,26.499779,35.368225,38.831726,32.643772,1.200000,1.200000,...,15.546833,27.359999,24.799999,5.196734,79.784920,89.598579,67.130730,0.171902,28.609579,2.016076e+09
1458,2016-07-11 00:00:00+00:00,51.0,29.256002,33.357262,25.623898,34.535168,39.551170,31.376312,0.500000,0.500000,...,11.246759,23.039999,23.520000,5.317598,72.347855,91.438370,50.855431,0.162606,28.425478,2.016076e+09

## Forming dataset

In [18]:
complete_incident_data = pd.merge(left=valid_incident_info, right=valid_incident_data, left_on="ID", right_on="associated_incident_id")

In [23]:
complete_incident_data.drop(columns=["date", "ID", "associated_incident_id"], inplace=True)

In [25]:
complete_incident_data

,incident_type,weather_code,temperature_2m_mean,temperature_2m_max,temperature_2m_min,apparent_temperature_mean,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,...,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,shortwave_radiation_sum,et0_fao_evapotranspiration,relative_humidity_2m_mean,relative_humidity_2m_max,relative_humidity_2m_min,soil_moisture_0_to_100cm_mean,soil_temperature_0_to_100cm_mean
0,"Wildlife (Animals, Insects, ect.)",61.0,26.181250,30.853739,23.222721,31.119635,37.405216,27.646168,3.700000,3.700000,...,8.0,15.685840,32.760002,20.340000,4.081936,86.535942,97.319748,67.104454,0.100330,27.059708
1,"Wildlife (Animals, Insects, ect.)",65.0,24.831251,28.726011,22.698296,29.675135,34.100143,27.605642,40.900002,40.900002,...,16.0,11.032987,32.760002,13.220000,2.638540,91.182335,98.795929,76.686935,0.111966,27.282877
2,"Wildlife (Animals, Insects, ect.)",63.0,25.320002,28.822502,23.418974,29.850115,32.781475,27.737570,13.900000,13.900000,...,16.0,18.391737,39.599998,16.770000,3.193541,90.186157,98.799850,72.203178,0.178233,26.044960
3,Soil Saturation,63.0,24.968752,30.912399,22.292822,29.667816,36.358009,26.794775,8.700001,8.700001,...,12.0,11.903159,29.879999,15.740000,3.191597,89.921196,100.000000,65.571266,0.135140,26.326019
4,Flood,63.0,26.777082,28.501064,24.950001,31.184931,32.895767,29.445236,9.800000,9.800000,...,10.0,21.252962,45.360001,16.320000,3.356593,85.609283,93.624374,77.118385,0.185335,27.878496
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1452,Extreme Heat,61.0,28.930170,32.800346,25.011164,35.103939,41.161266,30.888229,3.500000,3.500000,...,6.0,13.684735,23.039999,23.700001,5.090987,80.441078,95.925018,64.424858,0.221687,28.096649
1453,Extreme Heat,51.0,29.559919,35.065079,24.764378,34.819813,40.718952,30.542171,0.400000,0.400000,...,3.0,9.659814,27.359999,23.410000,5.393454,72.999016,97.347054,49.744556,0.162852,27.800879
1454,Extreme Heat,51.0,28.985748,30.460400,26.847189,35.060455,38.243690,32.108582,0.100000,0.100000,...,1.0,17.102840,23.759998,24.240000,5.076493,81.179146,89.624519,74.539909,0.213385,28.357355
1455,Extreme Heat,53.0,29.020836,31.750908,26.499779,35.368225,38.831726,32.643772,1.200000,1.200000,...,5.0,15.546833,27.359999,24.799999,5.196734,79.784920,89.598579,67.130730,0.171902,28.609579
1456,Soil Saturation,51.0,29.256002,33.357262,25.623898,34.535168,39.551170,31.376312,0.500000,0.500000,...,2.0,11.246759,23.039999,23.520000,5.317598,72.347855,91.438370,50.855431,0.162606,28.425478

In [26]:
complete_nonincident_data = invalid_incident_data

In [28]:
complete_nonincident_data.drop(columns=["associated_incident_id", "date"], inplace=True)

In [30]:
complete_nonincident_data["incident_type"] = "Not Incident"

In [33]:
total_data = pd.concat([complete_nonincident_data, complete_incident_data])

In [37]:
total_data.dropna(inplace=True)

In [47]:
total_data["is_incident"] = total_data["incident_type"] != "Not Incident"

In [51]:
total_data.to_csv("clean_dataset_v1.csv", index=False)